### ISSUE TITLE
Xuggler 5.4 issue | mvn build failure

### ISSUE THREAD

**Issue by ry6d3** [sensorstorm/StormCV#7]
[ERROR] Failed to execute goal on project stormcv-deploy: 
Could not resolve dependencies for project nl.tno.stormcv:stormcv-deploy:jar:0.0.1-SNAPSHOT: Failure to find xuggle:xuggle-xuggler:jar:5.4
 in http://github.com/sensorstorm/maven/raw/master/releases/ was cached in the local repository, 

 How to figure maven dependency for  xuggle:xuggle-xuggler:jar:5.4 or fix this issue?

**Comment by corneversloot** [comment]
The Xuggle repository at http://xuggle.googlecode.com/svn/trunk/repo/share/java/ does not exist anymore. I guess this has to do with the fact that Xuggle is not deprecated in favour of [Humble Video](https://github.com/artclarke/humble-video). This means that another video reader must be integrated into StormCV in order for it to work again. Someone else has to do it since I no longer actively maintain this project...

**Comment by RavikiranYadavalli** [comment]
I have downloaded the jar and added as a local maven dependency And build was successful.
https://github.com/lxb200709/xuggle/blob/master/repo/share/java/xuggle/xuggle-xuggler/5.4/xuggle-xuggler-5.4.jar
